// JavaScript source code

const types= {
    CREATE_CIRCLE: "CREATE_CIRCLE",
    CREATE_LINE: "CREATE_LINE",
    UPDATE_LINE: "UPDATE_LINE",
    TOOL_CHANGE: "TOOL_CHANGE",
    END_THE_SHAPE: "END_THE_SHAPE",
    SNAP_TO_FIRST: "SNAP_TO_FIRST",
    UPDATE_SHAPE: "UPDATE_SHAPE",
    ADD_NEW_TAB: "ADD_NEW_TAB",
    DELETE_A_TAB: "DELETE_A_TAB",
    LINE_TO_CURVE: 'LINE_TO_CURVE',
    UPDATE_CURVE: "UPDATE_CURVE",
    DE_SELECT: "DE_SELECT",
    LINE_CLICKED: "LINE_CLICKED",
    CURVE_CLICKED: "CURVE_CLICKED"
}
export default types;
